stages:
  - test

test-plone-4.3-py2:
  tags:
  - nix
  stage: test
  script:
  - BUILDOUT_CFG=test_plone43.cfg
    PLONE=plone43
    PYTHON=python27
    make nix-show
  - BUILDOUT_CFG=test_plone43.cfg
    BUILDOUT_ARGS="-N install pylama pocompile test"
    LC_ALL=C
    PLONE=plone43
    PYTHON=python27
    ROBOT_BROWSER=headlessfirefox
    make nix-test
  artifacts:
    paths:
      - parts/test

test-plone-5.2-py2:
  tags:
  - nix
  stage: test
  script:
  - BUILDOUT_CFG=test_plone52.cfg
    PLONE=plone52
    PYTHON=python27
    make nix-show
  - BUILDOUT_CFG=test_plone52.cfg
    BUILDOUT_ARGS="-N install pylama pocompile test"
    LC_ALL=C
    PLONE=plone52
    PYTHON=python27
    ROBOT_BROWSER=headlessfirefox
    make nix-test
  artifacts:
    paths:
      - parts/test

test-plone-5.2-py3:
  tags:
  - nix
  stage: test
  script:
  - BUILDOUT_CFG=test_plone52.cfg
    PLONE=plone52
    PYTHON=python37
    make nix-show
  - BUILDOUT_CFG=test_plone52.cfg
    BUILDOUT_ARGS="-N install black pylama pocompile test"
    LC_ALL=C
    PLONE=plone52
    PYTHON=python37
    ROBOT_BROWSER=headlessfirefox
    make nix-test
  artifacts:
    paths:
      - parts/test
